### ISSUE TITLE
Use this issue to change the colour

### ISSUE THREAD

**Issue by Damovisa** [DamovisaOrg/TailwindTraders-ADO40#9]
You can change the colour of the LIFX bulb by leaving a colour here.

**Comment by Damovisa** [comment]
Here's a comment that should trigger the workflow, but not change the colour.

**Comment by Damovisa** [comment]
#ff0000

**Comment by devjack** [comment]
Does it work from other users too? #f209cf

**Comment by devjack** [comment]
What about changing rapidly to #0adb42

**Comment by devjack** [comment]
and back again f209cf

**Comment by devjack** [comment]
I'm having way too much fun with this #8716dd

**Comment by devjack** [comment]
#f209cf

**Comment by devjack** [comment]
#0adb42

**Comment by devjack** [comment]
#f209cf

**Comment by rabwill** [comment]
#CD5C5C 😎

**Comment by Damovisa** [comment]
Ok, let's see if #ff0000 will work even if it's surrounded by text.

**Comment by Damovisa** [comment]
Hm, ok what about #ff0000 now?

**Comment by Damovisa** [comment]
This is like a double commit message just to set the light to #ff0000 or something.

**Comment by Damovisa** [comment]
New syntax. Oh yeah, #ff0000 for the colour, thanks.

**Comment by aaronpowell** [comment]
#FF00AA

**Comment by aaronpowell** [comment]
#C0FFEE

**Comment by aaronpowell** [comment]
#BADA55

**Comment by Damovisa** [comment]
#COFFEE

**Comment by Damovisa** [comment]
Oh, let's do a #C0FFEE one that actually works.

**Comment by Damovisa** [comment]
And one that doesn't have a colour?

**Comment by Damovisa** [comment]
And then another that #fff005 does.

**Comment by Damovisa** [comment]
This used to be broken.

**Comment by Damovisa** [comment]
Still was, apparently.

**Comment by Damovisa** [comment]
What about this as a solution...

**Comment by Damovisa** [comment]
Do the exit!!

**Comment by Damovisa** [comment]
But it works if you #ffff00 include a colour?

**Comment by Damovisa** [comment]
Yeah, #ff00ff seems to.

**Comment by Damovisa** [comment]
Ok, one with a #ff00ff colour.

**Comment by Damovisa** [comment]
And another without a colour!

**Comment by Damovisa** [comment]
Still fails?

**Comment by Damovisa** [comment]
With an else and default colour.

**Comment by Damovisa** [comment]
vkwjebkjaefw

**Comment by Damovisa** [comment]
vwaghraetdsfgerw

**Comment by Damovisa** [comment]
rberte

**Comment by Damovisa** [comment]
Ok, what about if we set -e

**Comment by Damovisa** [comment]
plus e?

**Comment by Damovisa** [comment]
gaweewa

**Comment by Damovisa** [comment]
vbageaewf

**Comment by Damovisa** [comment]
With a #ff0000...

**Comment by Damovisa** [comment]
And again with no valid colour code

**Comment by aaronpowell** [comment]
#FF00AA

**Comment by aaronpowell** [comment]
#C0FFEE

**Comment by Damovisa** [comment]
And #FF00AA aaa

**Comment by Damovisa** [comment]
Ooh yeah, #BADA55 colour!

**Comment by Damovisa** [comment]
Here's a colour! #0055DD
